### ISSUE TITLE
Use Docker on VPS?

### ISSUE THREAD

**Issue by mees-** [Bloomdex/2.2-docs#1]
This might cause a performance penalty but it allows us to nicely separate the webserver from the database. Please comment with what you think.

**Comment by LutzenH** [comment]
We could start using Docker and if the performance penalty is to high, just switch to bare-metal. If we mount a system folder we can always replace the container and run the process natively.

**Comment by mees-** [comment]
I think we can close this and conclude that we'll try using docker. If it works that's great but if we feel like docker is causing too much overhead we can ditch it again.
